### ISSUE TITLE
Voting System

### ISSUE THREAD

**Issue by Zhongbob** [RdeVCCA/RVHSGAMEJAM2024#3]
Create a normalised sql tables to handle the following:
1. Allow users to rate a specific game from 1 star to 5 star, including decimals in different categories
2. Allow users to rate a specific game in the following categories:
- General
- Relatedness to theme
- Aethestics
- Fun

The following are relevant tables in the database you will need to create and reference in your table:
users(**userId**,username,email)
submissions(**gameId**,name,description,creators,previews,link)

In addition, create a few .php files for the following purposes:
1. Create a file to submit a rating. If a user submits a rating which already has existed of a specific cateogory to a specific game, overwrite the old rating. Errors should be echoed out in json format, in the following form:
["success"=>bool, "error" =>"Error message"];

Create a few .inc.php files for the following purposes:
1. Create a file to retrieve the ratings of the current user for the current game. The current game's gameId will be stored as a GET variable "gameId". Save the ratings to a dictionary $ratings, which as the following keys:
[
"category"=>rating
]
For unrated categories, the rating should be initialised to null

The user's login information will be stored in a variable $userInfo. this variable is stored as a map, with the following keys:
["userid",
 "email", 
 "username"];
You may give a random initial value to $userInfo for testing purposes

**Comment by h-isthebestletter** [comment]
done
