### ISSUE TITLE
Comment system

### ISSUE THREAD

**Issue by Zhongbob** [RdeVCCA/RVHSGAMEJAM2024#4]
Create a normalised sql tables to handle the following:
1. Allow users to comment to a specific game 
2. Keep track of the time the user commented on said game. There should be a time limit of 30 second between each comment.

The following are relevant tables in the database you will need to create and reference in your table:
users(**userId**,username,email,pfp)
submissions(**gameId**,name,description,creators,previews,link)

In addition, create a few .php files for the following purposes:
1. Create a file to submit a comment. Output an error if the commenter has commented within the last 30 second. Errors should be echoed out in json format, in the following form:
["success"=>bool, "error" =>"Error message"];

Create a few .inc.php files for the following purposes:
1. Create a file to retrieve the comments for the current game. The current game's gameId will be stored as a GET variable "gameId". For each commenter, include his/her general rating if possible. If the user has yet to give a general rating, it should be set to NULL. Save the ratings to a list $comments, which stores a 2d array which contains each comment as a dictionary with the following keys:
[
"commenterName"
"commenterPfp"
"comment"
"generalRating"
]
For unrated categories, the rating should be initialised to null

The user's login information will be stored in a variable $userInfo. this variable is stored as a map, with the following keys:
["userid",
 "email", 
 "username"];
You may give a random initial value to $userInfo for testing purposes

**Comment by h-isthebestletter** [comment]
done
